CREATE DATABASE BANGALORE;
USE BANGALORE;
CREATE TABLE show_room(id int, show_room_name varchar(20), show_room_type varchar(20),show_room_loc varchar(20) unique,show_room_company varchar(20),company_country varchar(20),vehicle_price bigint not null, vehicle_color varchar(20), show_room_employees int,vehicle_insurance boolean);
INSERT INTO show_room VALUES(1, 'ABHAYA MOTORS', 'CAR', 'RR NAGAR', 'TOYOTA', 'JAPAN', 250000, 'BLUE', 5, TRUE);
INSERT INTO show_room VALUES(2, 'KALPANA MOTORS', 'BIKE', 'JP NAGAR', 'HONDA', 'JAPAN', 100000, 'BLACK', 15, TRUE);
INSERT INTO show_room VALUES(3, 'KEERTHI MOTORS', 'CAR', 'RAJAJI NAGAR', 'SUZUKI', 'JAPAN', 300000, 'RED', 25, TRUE);
INSERT INTO show_room VALUES(4, 'KAVYA MOTORS', 'CAR', 'MG ROAD', 'VOLKSWAGEN', 'GERMANY', 750000, 'GREY', 150, TRUE);
INSERT INTO show_room VALUES(5, 'SRINIVAS MOTORS', 'BIKE', 'DAVANAGERE', 'ADLER', 'GERMANY', 850000, 'BLUE', 5, TRUE);
INSERT INTO show_room VALUES(6, 'KALAVATHI MOTORS', 'CAR', 'SHIMOGA', 'BAJAJ', 'INDIA', 100000, 'BLACK', 20, TRUE);
INSERT INTO show_room VALUES(7, 'UDAY MOTORS', 'CAR', 'SAGAR', 'AUDI', 'GERMANY', 280000, 'BLUE', 30, TRUE);
INSERT INTO show_room VALUES(8, 'SHEELA MOTORS', 'BIKE', 'BHADRAVATHI', 'ALAN', 'ITALY', 100000, 'ORANGE', 125, TRUE);
INSERT INTO show_room VALUES(9, 'RAGHU MOTORS', 'CAR', 'HONNALI', 'APRILIA', 'ITALY', 1000000, 'GREY', 200, TRUE);
INSERT INTO show_room VALUES(10, 'VARUN MOTORS', 'CAR', 'HARIHARA', 'ASPARK', 'JAPAN', 980000, 'RED', 250, TRUE);
INSERT INTO show_room VALUES(11, 'NAMRATHA MOTORS', 'BIKE', 'MALEBENNUR', 'ARIEL', 'ENGLAND', 560000, 'BLACK', 330, TRUE);
INSERT INTO show_room VALUES(12, 'PAVAN MOTORS', 'CAR', 'HUBLI', 'ASHOK LEYLAND', 'INDIA', 300000, 'BLUE',225, TRUE);
INSERT INTO show_room VALUES(13, 'DARSHAN MOTORS', 'BIKE', 'DHARWAD', 'BH', 'SPAIN', 1000000, 'PURPLE', 280, TRUE);
INSERT INTO show_room VALUES(14, 'LAKSHMI MOTORS', 'BIKE', 'MADIKERI', 'BILENKY', 'USA', 200000, 'VIOLET', 185, TRUE);
INSERT INTO show_room VALUES(15, 'SRISHA MOTORS', 'CAR', 'UDUPI', 'FERRARI', 'ITALY', 3000000, 'DARK BLUE', 163, TRUE);
INSERT INTO show_room VALUES(16, 'SRINIDHI MOTORS', 'CAR', 'RAMNAGAR', 'BENZ', 'INDIA', 1000000, 'DEEP BLUE', 184, TRUE);
INSERT INTO show_room VALUES(17, 'SANJANA MOTORS', 'BIKE', 'CHITRADURGA', 'CALOI', 'BRAZIL', 100000, 'RED', 196, TRUE);
INSERT INTO show_room VALUES(18, 'SURABHI MOTORS', 'CAR', 'KOLAR', 'FIAT', 'ITALY', 8500000, 'BLUE', '260', TRUE);
INSERT INTO show_room VALUES(19, 'PRIYANKA MOTORS', 'CAR', 'MYSORE', 'FORD', 'USA', 1000000, 'YELLOW', 233, TRUE);
INSERT INTO show_room VALUES(20, 'BHARATH MOTORS', 'CAR', 'HAMPI', 'HERO', 'INDIA', 850000, 'BLACK', 155, TRUE);
ALTER TABLE show_room MODIFY show_room_employees int not null;
ALTER TABLE show_room MODIFY show_room_name varchar(20) unique;
ALTER TABLE show_room MODIFY vehicle_price bigint check (vehicle_price > 10000);



USE BANGALORE;
CREATE TABLE chat_center(id int, chat_center_name varchar(20), chat_name varchar(20),chat_center_loc varchar(20) unique,chat_ratings int,chat_price int not null, found_through varchar(20), center_year varchar(20),delivery_option boolean,chat_good boolean);
INSERT INTO chat_center VALUES(1, 'ABHAYA CHAT CENTER', 'CAR', 'RR NAGAR', 'TOYOTA', 'JAPAN', 250000, 'BLUE', 5, TRUE);
INSERT INTO chat_center VALUES(2, 'KALPANA CHAT CENTER', 'BIKE', 'JP NAGAR', 'HONDA', 'JAPAN', 100000, 'BLACK', 15, TRUE);
INSERT INTO chat_center VALUES(3, 'KEERTHI CHAT CENTER', 'CAR', 'RAJAJI NAGAR', 'SUZUKI', 'JAPAN', 300000, 'RED', 25, TRUE);
INSERT INTO chat_center VALUES(4, 'KAVYA CHAT CENTER', 'CAR', 'MG ROAD', 'VOLKSWAGEN', 'GERMANY', 750000, 'GREY', 150, TRUE);
INSERT INTO chat_center VALUES(5, 'SRINIVAS CHAT CENTER', 'BIKE', 'DAVANAGERE', 'ADLER', 'GERMANY', 850000, 'BLUE', 5, TRUE);
INSERT INTO chat_center VALUES(6, 'KALAVATHI CHAT CENTER', 'CAR', 'SHIMOGA', 'BAJAJ', 'INDIA', 100000, 'BLACK', 20, TRUE);
INSERT INTO chat_center VALUES(7, 'UDAY CHAT CENTER', 'CAR', 'SAGAR', 'AUDI', 'GERMANY', 280000, 'BLUE', 30, TRUE);
INSERT INTO chat_center VALUES(8, 'SHEELA CHAT CENTER', 'BIKE', 'BHADRAVATHI', 'ALAN', 'ITALY', 100000, 'ORANGE', 125, TRUE);
INSERT INTO chat_center VALUES(9, 'RAGHU CHAT CENTER', 'CAR', 'HONNALI', 'APRILIA', 'ITALY', 1000000, 'GREY', 200, TRUE);
INSERT INTO chat_center VALUES(10, 'VARUN CHAT CENTER', 'CAR', 'HARIHARA', 'ASPARK', 'JAPAN', 980000, 'RED', 250, TRUE);
INSERT INTO chat_center VALUES(11, 'NAMRATHA CHAT CENTER', 'BIKE', 'MALEBENNUR', 'ARIEL', 'ENGLAND', 560000, 'BLACK', 330, TRUE);
INSERT INTO chat_center VALUES(12, 'PAVAN CHAT CENTER', 'CAR', 'HUBLI', 'ASHOK LEYLAND', 'INDIA', 300000, 'BLUE',225, TRUE);
INSERT INTO chat_center VALUES(13, 'DARSHAN CHAT CENTER', 'BIKE', 'DHARWAD', 'BH', 'SPAIN', 1000000, 'PURPLE', 280, TRUE);
INSERT INTO chat_center VALUES(14, 'LAKSHMI CHAT CENTER', 'BIKE', 'MADIKERI', 'BILENKY', 'USA', 200000, 'VIOLET', 185, TRUE);
INSERT INTO chat_center VALUES(15, 'SRISHA CHAT CENTER', 'CAR', 'UDUPI', 'FERRARI', 'ITALY', 3000000, 'DARK BLUE', 163, TRUE);
INSERT INTO chat_center VALUES(16, 'SRINIDHI CHAT CENTER', 'CAR', 'RAMNAGAR', 'BENZ', 'INDIA', 1000000, 'DEEP BLUE', 184, TRUE);
INSERT INTO chat_center VALUES(17, 'SANJANA CHAT CENTER', 'BIKE', 'CHITRADURGA', 'CALOI', 'BRAZIL', 100000, 'RED', 196, TRUE);
INSERT INTO chat_center VALUES(18, 'SURABHI CHAT CENTER', 'CAR', 'KOLAR', 'FIAT', 'ITALY', 8500000, 'BLUE', '260', TRUE);
INSERT INTO chat_center VALUES(19, 'PRIYANKA CHAT CENTER', 'CAR', 'MYSORE', 'FORD', 'USA', 1000000, 'YELLOW', 233, TRUE);
INSERT INTO chat_center VALUES(20, 'BHARATH CHAT CENTER', 'CAR', 'HAMPI', 'HERO', 'INDIA', 850000, 'BLACK', 155, TRUE);
ALTER TABLE chat_center MODIFY show_room_employees int not null;
ALTER TABLE chat_center MODIFY show_room_name varchar(20) unique;
ALTER TABLE chat_center MODIFY vehicle_price bigint check(vehicle_price > 10000);





USE BANGALORE;
CREATE TABLE temple_info(id int, temple_name varchar(20), temple_loc varchar(20) unique,built_by varchar(20), built_year bigint,temple_timings varchar(20),vehicle_price bigint not null, vehicle_color varchar(20), show_room_employees int,temple_good boolean);
INSERT INTO temple_info VALUES(1, 'ABHAYA MOTORS', 'CAR', 'RR NAGAR', 'TOYOTA', 'JAPAN', 250000, 'BLUE', 5, TRUE);
INSERT INTO temple_info VALUES(2, 'KALPANA MOTORS', 'BIKE', 'JP NAGAR', 'HONDA', 'JAPAN', 100000, 'BLACK', 15, TRUE);
INSERT INTO temple_info VALUES(3, 'KEERTHI MOTORS', 'CAR', 'RAJAJI NAGAR', 'SUZUKI', 'JAPAN', 300000, 'RED', 25, TRUE);
INSERT INTO temple_info VALUES(4, 'KAVYA MOTORS', 'CAR', 'MG ROAD', 'VOLKSWAGEN', 'GERMANY', 750000, 'GREY', 150, TRUE);
INSERT INTO temple_info VALUES(5, 'SRINIVAS MOTORS', 'BIKE', 'DAVANAGERE', 'ADLER', 'GERMANY', 850000, 'BLUE', 5, TRUE);
INSERT INTO temple_info VALUES(6, 'KALAVATHI MOTORS', 'CAR', 'SHIMOGA', 'BAJAJ', 'INDIA', 100000, 'BLACK', 20, TRUE);
INSERT INTO temple_info VALUES(7, 'UDAY MOTORS', 'CAR', 'SAGAR', 'AUDI', 'GERMANY', 280000, 'BLUE', 30, TRUE);
INSERT INTO temple_info VALUES(8, 'SHEELA MOTORS', 'BIKE', 'BHADRAVATHI', 'ALAN', 'ITALY', 100000, 'ORANGE', 125, TRUE);
INSERT INTO show_room VALUES(9, 'RAGHU MOTORS', 'CAR', 'HONNALI', 'APRILIA', 'ITALY', 1000000, 'GREY', 200, TRUE);
INSERT INTO temple_info VALUES(10, 'VARUN MOTORS', 'CAR', 'HARIHARA', 'ASPARK', 'JAPAN', 980000, 'RED', 250, TRUE);
INSERT INTO temple_info VALUES(11, 'NAMRATHA MOTORS', 'BIKE', 'MALEBENNUR', 'ARIEL', 'ENGLAND', 560000, 'BLACK', 330, TRUE);
INSERT INTO temple_info VALUES(12, 'PAVAN MOTORS', 'CAR', 'HUBLI', 'ASHOK LEYLAND', 'INDIA', 300000, 'BLUE',225, TRUE);
INSERT INTO temple_info VALUES(13, 'DARSHAN MOTORS', 'BIKE', 'DHARWAD', 'BH', 'SPAIN', 1000000, 'PURPLE', 280, TRUE);
INSERT INTO temple_info VALUES(14, 'LAKSHMI MOTORS', 'BIKE', 'MADIKERI', 'BILENKY', 'USA', 200000, 'VIOLET', 185, TRUE);
INSERT INTO temple_info VALUES(15, 'SRISHA MOTORS', 'CAR', 'UDUPI', 'FERRARI', 'ITALY', 3000000, 'DARK BLUE', 163, TRUE);
INSERT INTO temple_info VALUES(16, 'SRINIDHI MOTORS', 'CAR', 'RAMNAGAR', 'BENZ', 'INDIA', 1000000, 'DEEP BLUE', 184, TRUE);
INSERT INTO temple_info VALUES(17, 'SANJANA MOTORS', 'BIKE', 'CHITRADURGA', 'CALOI', 'BRAZIL', 100000, 'RED', 196, TRUE);
INSERT INTO temple_info VALUES(18, 'SURABHI MOTORS', 'CAR', 'KOLAR', 'FIAT', 'ITALY', 8500000, 'BLUE', '260', TRUE);
INSERT INTO temple_info VALUES(19, 'PRIYANKA MOTORS', 'CAR', 'MYSORE', 'FORD', 'USA', 1000000, 'YELLOW', 233, TRUE);
INSERT INTO temple_info VALUES(20, 'BHARATH MOTORS', 'CAR', 'HAMPI', 'HERO', 'INDIA', 850000, 'BLACK', 155, TRUE);
ALTER TABLE temple_info MODIFY show_room_employees int not null;
ALTER TABLE temple_info MODIFY show_room_name varchar(20) unique;
ALTER TABLE temple_info MODIFY vehicle_price bigint check(vehicle_price > 10000);

USE BANGALORE;
CREATE TABLE market_info(id int, show_room_name varchar(20), show_room_type varchar(20),show_room_loc varchar(20) unique,show_room_company varchar(20),company_country varchar(20),vehicle_price bigint not null, vehicle_color varchar(20), show_room_employees int,vehicle_insurance boolean);
INSERT INTO market_info VALUES(1, 'ABHAYA MOTORS', 'CAR', 'RR NAGAR', 'TOYOTA', 'JAPAN', 250000, 'BLUE', 5, TRUE);
INSERT INTO market_info VALUES(2, 'KALPANA MOTORS', 'BIKE', 'JP NAGAR', 'HONDA', 'JAPAN', 100000, 'BLACK', 15, TRUE);
INSERT INTO market_info VALUES(3, 'KEERTHI MOTORS', 'CAR', 'RAJAJI NAGAR', 'SUZUKI', 'JAPAN', 300000, 'RED', 25, TRUE);
INSERT INTO market_info VALUES(4, 'KAVYA MOTORS', 'CAR', 'MG ROAD', 'VOLKSWAGEN', 'GERMANY', 750000, 'GREY', 150, TRUE);
INSERT INTO market_info VALUES(5, 'SRINIVAS MOTORS', 'BIKE', 'DAVANAGERE', 'ADLER', 'GERMANY', 850000, 'BLUE', 5, TRUE);
INSERT INTO market_info VALUES(6, 'KALAVATHI MOTORS', 'CAR', 'SHIMOGA', 'BAJAJ', 'INDIA', 100000, 'BLACK', 20, TRUE);
INSERT INTO market_info VALUES(7, 'UDAY MOTORS', 'CAR', 'SAGAR', 'AUDI', 'GERMANY', 280000, 'BLUE', 30, TRUE);
INSERT INTO market_info VALUES(8, 'SHEELA MOTORS', 'BIKE', 'BHADRAVATHI', 'ALAN', 'ITALY', 100000, 'ORANGE', 125, TRUE);
INSERT INTO market_info VALUES(9, 'RAGHU MOTORS', 'CAR', 'HONNALI', 'APRILIA', 'ITALY', 1000000, 'GREY', 200, TRUE);
INSERT INTO market_info VALUES(10, 'VARUN MOTORS', 'CAR', 'HARIHARA', 'ASPARK', 'JAPAN', 980000, 'RED', 250, TRUE);
INSERT INTO market_info VALUES(11, 'NAMRATHA MOTORS', 'BIKE', 'MALEBENNUR', 'ARIEL', 'ENGLAND', 560000, 'BLACK', 330, TRUE);
INSERT INTO market_info VALUES(12, 'PAVAN MOTORS', 'CAR', 'HUBLI', 'ASHOK LEYLAND', 'INDIA', 300000, 'BLUE',225, TRUE);
INSERT INTO market_info VALUES(13, 'DARSHAN MOTORS', 'BIKE', 'DHARWAD', 'BH', 'SPAIN', 1000000, 'PURPLE', 280, TRUE);
INSERT INTO market_info VALUES(14, 'LAKSHMI MOTORS', 'BIKE', 'MADIKERI', 'BILENKY', 'USA', 200000, 'VIOLET', 185, TRUE);
INSERT INTO market_info VALUES(15, 'SRISHA MOTORS', 'CAR', 'UDUPI', 'FERRARI', 'ITALY', 3000000, 'DARK BLUE', 163, TRUE);
INSERT INTO market_info VALUES(16, 'SRINIDHI MOTORS', 'CAR', 'RAMNAGAR', 'BENZ', 'INDIA', 1000000, 'DEEP BLUE', 184, TRUE);
INSERT INTO market_info VALUES(17, 'SANJANA MOTORS', 'BIKE', 'CHITRADURGA', 'CALOI', 'BRAZIL', 100000, 'RED', 196, TRUE);
INSERT INTO market_info VALUES(18, 'SURABHI MOTORS', 'CAR', 'KOLAR', 'FIAT', 'ITALY', 8500000, 'BLUE', '260', TRUE);
INSERT INTO market_info VALUES(19, 'PRIYANKA MOTORS', 'CAR', 'MYSORE', 'FORD', 'USA', 1000000, 'YELLOW', 233, TRUE);
INSERT INTO market_info VALUES(20, 'BHARATH MOTORS', 'CAR', 'HAMPI', 'HERO', 'INDIA', 850000, 'BLACK', 155, TRUE);
ALTER TABLE market_info MODIFY show_room_employees int not null;
ALTER TABLE market_info MODIFY show_room_name varchar(20) unique;
ALTER TABLE market_info MODIFY vehicle_price bigint check(vehicle_price > 10000);






USE BANGALORE;
CREATE TABLE metro_info(id int, show_room_name varchar(20), show_room_type varchar(20),show_room_loc varchar(20) unique,show_room_company varchar(20),company_country varchar(20),vehicle_price bigint not null, vehicle_color varchar(20), show_room_employees int,vehicle_insurance boolean);
INSERT INTO metro_info VALUES(1, 'ABHAYA MOTORS', 'CAR', 'RR NAGAR', 'TOYOTA', 'JAPAN', 250000, 'BLUE', 5, TRUE);
INSERT INTO metro_info VALUES(2, 'KALPANA MOTORS', 'BIKE', 'JP NAGAR', 'HONDA', 'JAPAN', 100000, 'BLACK', 15, TRUE);
INSERT INTO metro_info VALUES(3, 'KEERTHI MOTORS', 'CAR', 'RAJAJI NAGAR', 'SUZUKI', 'JAPAN', 300000, 'RED', 25, TRUE);
INSERT INTO metro_info VALUES(4, 'KAVYA MOTORS', 'CAR', 'MG ROAD', 'VOLKSWAGEN', 'GERMANY', 750000, 'GREY', 150, TRUE);
INSERT INTO metro_info VALUES(5, 'SRINIVAS MOTORS', 'BIKE', 'DAVANAGERE', 'ADLER', 'GERMANY', 850000, 'BLUE', 5, TRUE);
INSERT INTO metro_info VALUES(6, 'KALAVATHI MOTORS', 'CAR', 'SHIMOGA', 'BAJAJ', 'INDIA', 100000, 'BLACK', 20, TRUE);
INSERT INTO metro_info VALUES(7, 'UDAY MOTORS', 'CAR', 'SAGAR', 'AUDI', 'GERMANY', 280000, 'BLUE', 30, TRUE);
INSERT INTO metro_info VALUES(8, 'SHEELA MOTORS', 'BIKE', 'BHADRAVATHI', 'ALAN', 'ITALY', 100000, 'ORANGE', 125, TRUE);
INSERT INTO metro_info VALUES(9, 'RAGHU MOTORS', 'CAR', 'HONNALI', 'APRILIA', 'ITALY', 1000000, 'GREY', 200, TRUE);
INSERT INTO metro_info VALUES(10, 'VARUN MOTORS', 'CAR', 'HARIHARA', 'ASPARK', 'JAPAN', 980000, 'RED', 250, TRUE);
INSERT INTO metro_info VALUES(11, 'NAMRATHA MOTORS', 'BIKE', 'MALEBENNUR', 'ARIEL', 'ENGLAND', 560000, 'BLACK', 330, TRUE);
INSERT INTO metro_info VALUES(12, 'PAVAN MOTORS', 'CAR', 'HUBLI', 'ASHOK LEYLAND', 'INDIA', 300000, 'BLUE',225, TRUE);
INSERT INTO metro_info VALUES(13, 'DARSHAN MOTORS', 'BIKE', 'DHARWAD', 'BH', 'SPAIN', 1000000, 'PURPLE', 280, TRUE);
INSERT INTO metro_info VALUES(14, 'LAKSHMI MOTORS', 'BIKE', 'MADIKERI', 'BILENKY', 'USA', 200000, 'VIOLET', 185, TRUE);
INSERT INTO metro_info VALUES(15, 'SRISHA MOTORS', 'CAR', 'UDUPI', 'FERRARI', 'ITALY', 3000000, 'DARK BLUE', 163, TRUE);
INSERT INTO metro_info VALUES(16, 'SRINIDHI MOTORS', 'CAR', 'RAMNAGAR', 'BENZ', 'INDIA', 1000000, 'DEEP BLUE', 184, TRUE);
INSERT INTO metro_info VALUES(17, 'SANJANA MOTORS', 'BIKE', 'CHITRADURGA', 'CALOI', 'BRAZIL', 100000, 'RED', 196, TRUE);
INSERT INTO metro_info VALUES(18, 'SURABHI MOTORS', 'CAR', 'KOLAR', 'FIAT', 'ITALY', 8500000, 'BLUE', '260', TRUE);
INSERT INTO metro_info VALUES(19, 'PRIYANKA MOTORS', 'CAR', 'MYSORE', 'FORD', 'USA', 1000000, 'YELLOW', 233, TRUE);
INSERT INTO metro_info VALUES(20, 'BHARATH MOTORS', 'CAR', 'HAMPI', 'HERO', 'INDIA', 850000, 'BLACK', 155, TRUE);
ALTER TABLE metro_info MODIFY show_room_employees int not null;
ALTER TABLE metro_info MODIFY show_room_name varchar(20) unique;
ALTER TABLE metro_info MODIFY vehicle_price bigint check(vehicle_price > 10000);


